### PR TITLE
Update casino.js / Added warzone-stats to plugins

### PR DESCRIPTION
**Pull request by Wikinger1988**
intercept the input !casino without data.args or deviating data.args.

### CODE REVIEW

**Comment by muratulashozturk** [comment]
Nice one 🤣 I am actually lazy to do that XD. I have other things to working on. I will add more things to casino stuffs. Thansk for adding this btw.

**Comment by Rehkloos** [comment]
no way to squash these commits together and not have 2 separate commits

**Comment by Wikinger1988** [comment]
> 
> 
> no way to squash these commits together and not have 2 separate commits

sorry if i did something wrong. I'm still new to GitHub.

**Comment by Rehkloos** [comment]
warzone implement should be its out git branch and pull request

**Comment by Wikinger1988** [comment]
> 
> 
> There is nothing in the README.md for the warzone stats. <.<

done :)

**Pull request merged**
